# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: prod

   # datasource
   datasource:
      username: weboard
      password: weboard
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://localhost:3306/weboard?characterEncoding=utf8
      hikari:
         minimum-idle: 100
         maximum-pool-size: 200

# custom property
fileupload:
   urlBasePath: /upload-images
   fileSaveBasePath: /home/douzoneys/frontend/build/upload-images
   resourceMapping: ${fileupload.urlBasePath}/**
   fileUploadLocation: file:${fileupload.fileSaveBasePath}/